/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayl_eventos_reservas;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Font;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;

/**
 *
 * @author agust
 */
public class editarEvento extends javax.swing.JFrame {

    GestorBD gestor = new GestorBD();
    private int idReserva;
    private static int idCliente;
    private String fecha;
    private String horario;
    private String hora;
    private int cantAdultos;
    private int cantChicos;
    private String localidad;
    private String direccion;
    private float precio;
    private boolean señado;
    private int seña;
    
    /**
     * Creates new form agregarEvento
     */
    
    public editarEvento(int idReserva) {
        initComponents();
        this.idReserva = idReserva;
        setearTabla();
        setearDatos();
        
        
        personalizarTabla(this.tablaEntradas1);
        personalizarTabla(this.tablaVariedades1);
        
        Font subtitulo = new Font("Roboto Medium", Font.PLAIN, 20);
        Font conteo = new Font("Roboto Medium", Font.PLAIN, 16);
        Font texto = new Font("Roboto", Font.PLAIN, 14);
        Color c1 = new Color(255,255,255);
        
        this.labelEvento.setFont(new Font("Roboto Medium", Font.BOLD, 26));
        this.labelEvento.setForeground(c1);
        
        this.labelEntradas.setFont(subtitulo);
        this.labelEntradas.setForeground(c1);
        this.labelVariedades.setFont(subtitulo);
        this.labelVariedades.setForeground(c1);
        
        this.labelAdultos.setFont(texto);
        this.labelAdultos.setForeground(c1);
        this.labelFecha.setFont(texto);
        this.labelFecha.setForeground(c1);
        this.labelHorario.setFont(texto);
        this.labelHorario.setForeground(c1);
        this.labelLocalidad.setFont(texto);
        this.labelLocalidad.setForeground(c1);
        this.labelPrecio.setFont(texto);
        this.labelPrecio.setForeground(c1);
        this.radioSeñado.setFont(texto);
        this.radioSeñado.setForeground(c1);  //hora,direccion,niños,seña
        this.labelHora.setFont(texto);
        this.labelHora.setForeground(c1);
        this.labelDireccion.setFont(texto);
        this.labelDireccion.setForeground(c1);
        this.labelNiños.setFont(texto);
        this.labelNiños.setForeground(c1);
        this.labelSeña.setFont(texto);
        this.labelSeña.setForeground(c1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelEvento = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        campoHorario = new javax.swing.JComboBox<>();
        labelHorario = new javax.swing.JLabel();
        campoLocalidad = new javax.swing.JTextField();
        labelAdultos = new javax.swing.JLabel();
        labelLocalidad = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        radioSeñado = new javax.swing.JRadioButton();
        campoFecha = new com.toedter.calendar.JDateChooser();
        labelVariedades = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVariedades1 = new javax.swing.JTable();
        labelEntradas = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEntradas1 = new javax.swing.JTable();
        panelGuardar = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JLabel();
        campoHora = new javax.swing.JTextField();
        labelHora = new javax.swing.JLabel();
        campoSeña = new javax.swing.JSpinner();
        labelNiños = new javax.swing.JLabel();
        campoChicos = new javax.swing.JSpinner();
        campoDireccion = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        labelSeña = new javax.swing.JLabel();
        campoAdultos1 = new javax.swing.JSpinner();
        campoPrecio = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(154, 12, 26));

        labelEvento.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        labelEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEvento.setText("Evento");

        labelFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFecha.setText("Fecha");

        campoHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mediodia", "Tarde", "Noche" }));
        campoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHorarioActionPerformed(evt);
            }
        });

        labelHorario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelHorario.setText("Horario");

        campoLocalidad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLocalidadActionPerformed(evt);
            }
        });

        labelAdultos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAdultos.setText("Adultos");

        labelLocalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLocalidad.setText("Localidad");

        labelPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPrecio.setText("Precio");

        radioSeñado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioSeñado.setText("Señado");
        radioSeñado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSeñadoActionPerformed(evt);
            }
        });

        campoFecha.setBackground(new java.awt.Color(154, 12, 26));
        campoFecha.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        labelVariedades.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelVariedades.setText("Variedades");

        tablaVariedades1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Tipo"
            }
        ));
        tablaVariedades1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaVariedades1);
        if (tablaVariedades1.getColumnModel().getColumnCount() > 0) {
            tablaVariedades1.getColumnModel().getColumn(0).setResizable(false);
        }

        labelEntradas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelEntradas.setText("Entradas");

        tablaEntradas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Tipo"
            }
        ));
        tablaEntradas1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tablaEntradas1);

        panelGuardar.setBackground(new java.awt.Color(48, 48, 186));

        botonGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonGuardar.setText("Guardar");
        botonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        campoHora.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHoraActionPerformed(evt);
            }
        });

        labelHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelHora.setText("Hora");

        campoSeña.setRequestFocusEnabled(false);
        campoSeña.setValue(0);

        labelNiños.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNiños.setText("Niños");

        campoDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionActionPerformed(evt);
            }
        });

        labelDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDireccion.setText("Direccion");

        labelSeña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSeña.setText("Seña");

        campoAdultos1.setRequestFocusEnabled(false);
        campoAdultos1.setValue(25);

        campoPrecio.setRequestFocusEnabled(false);
        campoPrecio.setValue(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVariedades)
                    .addComponent(labelEntradas)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFecha)
                            .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAdultos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHorario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoHora)
                            .addComponent(labelHora, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                    .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSeña, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoPrecio)
                                .addGap(30, 30, 30)
                                .addComponent(campoSeña, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(radioSeñado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoAdultos1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNiños)
                            .addComponent(campoChicos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEvento)
                .addGap(376, 376, 376))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelEvento)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelVariedades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelEntradas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelFecha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelHora)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNiños)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoChicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelAdultos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAdultos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDireccion)
                            .addComponent(labelLocalidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSeña)
                            .addComponent(labelPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioSeñado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoSeña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181)
                        .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalizarTabla(JTable table){
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(Color.yellow);
        table.getTableHeader().setForeground(new Color(20,20,20)); 
        table.setRowHeight(26);
        table.setFont(new Font("Roboto",Font.PLAIN,14));
        
        table.getColumnModel().getColumn(0).setPreferredWidth(180);
        table.getColumnModel().getColumn(1).setPreferredWidth(80);
        table.getColumnModel().getColumn(2).setPreferredWidth(10);
    }
    
    private void campoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHorarioActionPerformed

    private void campoLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLocalidadActionPerformed

    private void radioSeñadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSeñadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSeñadoActionPerformed

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        if(!(campoFecha.getDate()==null) && !("".equals(campoLocalidad.getText()))){
            if(guardarEvento() && guardarVarEntr()){
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "El evento se ha editado exitosamente");
            }else{
                JOptionPane.showMessageDialog(null, "Se produjo un error.\nRevisa los datos ingresados", "Error", 0);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete los campos", "Completar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarMouseClicked

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
        botonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(100, 100, 240), new java.awt.Color(100, 120, 240), new java.awt.Color(25, 33, 136), new java.awt.Color(25, 33, 136)));
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited
        botonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    }//GEN-LAST:event_botonGuardarMouseExited

    private void campoHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHoraActionPerformed

    private void campoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionActionPerformed

    private boolean guardarVarEntr(){
        gestor.eliminarVarEntr(this.idReserva);
        ArrayList<Object[]> variedadesSeleccionadas = new ArrayList();
        for(int i=0 ; i < this.tablaVariedades1.getRowCount() ; i++){
            if(this.seleccionado(i, 2, tablaVariedades1)){
                Object[] variedadSeleccionada = new Object[2];
                variedadSeleccionada[0] = tablaVariedades1.getValueAt(i, 0);
                variedadSeleccionada[1] = tablaVariedades1.getValueAt(i, 1);
                variedadesSeleccionadas.add(variedadSeleccionada);
            }
        }
        
        ArrayList<Object[]> entradasSeleccionadas = new ArrayList();
        for(int i=0 ; i < this.tablaEntradas1.getRowCount() ; i++){
            if(this.seleccionado(i, 2, tablaEntradas1)){
                Object[] entradaSeleccionada = new Object[2];
                entradaSeleccionada[0] = tablaEntradas1.getValueAt(i, 0);
                entradaSeleccionada[1] = tablaEntradas1.getValueAt(i, 1);
                entradasSeleccionadas.add(entradaSeleccionada);
            }
        }
        
        if(gestor.registrarVarEntr(variedadesSeleccionadas, entradasSeleccionadas)){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean guardarEvento(){
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        this.fecha = df.format(campoFecha.getDate());
        this.horario = (String)this.campoHorario.getSelectedItem();
        this.hora = this.campoHora.getText();
        this.cantAdultos = (int)this.campoAdultos1.getValue();
        this.cantChicos = (int)this.campoChicos.getValue();
        this.localidad = this.campoLocalidad.getText();
        this.direccion = this.campoDireccion.getText();
        this.precio = (int)this.campoPrecio.getValue();
        this.señado = this.radioSeñado.isSelected();
        this.seña = (int)this.campoSeña.getValue();
        if(gestor.editarEvento(this.idReserva, fecha, horario, hora, cantAdultos, cantChicos, localidad, direccion, precio, señado, seña)){
            return true;
        }else{
            return false;
        }
    }
    
    private void setearDatos(){
        Vector<Vector<String>> registro = gestor.dameUnRegistro(this.idReserva);
        //"ID","Nombre", "Adultos", "Niños", "Localidad", "Direccion", "Fecha", "Horario", "Hora","Precio","Señado", "Seña"
        this.campoAdultos1.setValue(Integer.valueOf(registro.get(0).get(2)));
        this.campoChicos.setValue(Integer.valueOf(registro.get(0).get(3)));
        this.campoLocalidad.setText(registro.get(0).get(4));
        this.campoDireccion.setText(registro.get(0).get(5));
        
        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date fech=null;
        try{
            fech = df.parse(registro.get(0).get(6));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Se produjo un error en la fecha.\nVuelve a intentarlo", "Error", 0);
        }
        this.campoFecha.setDate(fech);
        
        this.campoHorario.setSelectedItem(registro.get(0).get(7));
        this.campoHora.setText(registro.get(0).get(8));
        this.campoPrecio.setValue(Integer.valueOf(registro.get(0).get(9)));
        boolean estaSeñado = false;
        if(registro.get(0).get(10).equals("1")){
            señado = true;
        }
        this.radioSeñado.setSelected(señado);
        this.campoSeña.setValue(Integer.valueOf(registro.get(0).get(11)));
        
        /*
        //SETEAR VARIEDADES
        int count = 0;
        for(int i = 1 ; i < registro.size() ; i++){
            if("variedad".equals(registro.get(i).get(1)) || "variedadextra".equals(registro.get(i).get(1))){
                count++;
            }
        }

        Object[][] varied = new Object[count][2];
        for(int i = 1 ; i <= count; i++){
            varied[i-1][0] = registro.get(i).get(0);
            varied[i-1][1] = registro.get(i).get(1);
        }
        
        for(int i = 0; i <= tablaVariedades1.getRowCount()-1; i++){
            
            for(int j = 0; j <= varied.length-1; j++){
                if (tablaVariedades1.getValueAt(i, 0).equals(varied[j][0])){
                    //
                }
            }
            
        }
        
        tablaVariedades1.setModel(new javax.swing.table.DefaultTableModel(
            varied,
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        //SETEAR ENTRADAS
        int count2 = 0;
        for(int i = 1 ; i < registro.size() ; i++){
            if("entrada".equals(registro.get(i).get(1)) || "entradaespecial".equals(registro.get(i).get(1))){
                count2++;
            }
        }

        Object[][] entr = new Object[count2][2];
        int c = 0;
        for(int i = 1 ; i < registro.size(); i++){
            if("entrada".equals(registro.get(i).get(1)) || "entradaespecial".equals(registro.get(i).get(1))){
                entr[c][0] = registro.get(i).get(0);
                entr[c][1] = registro.get(i).get(1);
                c++;
            }
        }

        tablaEntradas1.setModel(new javax.swing.table.DefaultTableModel(
            entr,
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });*/
    }
    
    private void setearTabla(){        
        Vector<Vector<String>> VectorVariedades = gestor.dameLasVariedades();
        Object[][] objetos = gestor.vectorObjetoConvertir(VectorVariedades);
             
        this.tablaVariedades1.setModel(new javax.swing.table.DefaultTableModel(
            objetos,
            new String [] {
                "Variedad","Tipo",""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        this.añadirCheckbox(2, tablaVariedades1);
        
        Vector<Vector<String>> VectorEntradas = gestor.dameLasEntradas();
        Object[][] objetos2 = gestor.vectorObjetoConvertir(VectorEntradas);

        this.tablaEntradas1.setModel(new javax.swing.table.DefaultTableModel(
            objetos2,
            new String [] {
                "Entrada","Tipo",""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        this.añadirCheckbox(2, tablaEntradas1);
    }
    
    public void añadirCheckbox(int column, JTable table){
	TableColumn tc = table.getColumnModel().getColumn(column);
	tc.setCellEditor(table.getDefaultEditor(Boolean.class));
	tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }
    
    public boolean seleccionado(int row, int column, JTable table){
	return table.getValueAt(row, column) != null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarEvento(idCliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonGuardar;
    private javax.swing.JSpinner campoAdultos1;
    private javax.swing.JSpinner campoChicos;
    private javax.swing.JTextField campoDireccion;
    private com.toedter.calendar.JDateChooser campoFecha;
    private javax.swing.JTextField campoHora;
    private javax.swing.JComboBox<String> campoHorario;
    private javax.swing.JTextField campoLocalidad;
    private javax.swing.JSpinner campoPrecio;
    private javax.swing.JSpinner campoSeña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAdultos;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEntradas;
    private javax.swing.JLabel labelEvento;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelHorario;
    private javax.swing.JLabel labelLocalidad;
    private javax.swing.JLabel labelNiños;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelSeña;
    private javax.swing.JLabel labelVariedades;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JRadioButton radioSeñado;
    private javax.swing.JTable tablaEntradas1;
    private javax.swing.JTable tablaVariedades1;
    // End of variables declaration//GEN-END:variables
}
