/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayl_eventos_reservas;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Soft 04
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
    */
    
    GestorBD gestor = new GestorBD();
    
    
    public VentanaPrincipal() {
        initComponents();
        
        personalizarTablaEventos();
        
        personalizarTabla(tablaVariedades);
        
        personalizarTabla(tablaEntradas);        
        
        Font subtitulo = new Font("Roboto Medium", Font.PLAIN, 18);
        Font texto = new Font("Roboto", Font.PLAIN, 14);
        Color c1 = new Color(255,255,255);
        
        tituloLista.setFont(new Font("Roboto", Font.BOLD, 26));
        tituloLista.setForeground(new Color(0,0,0));
        TituloDetalles.setFont(new Font("Roboto Medium", Font.BOLD, 26));
        TituloDetalles.setForeground(c1);
        
        this.LabelEntradas.setFont(subtitulo);
        this.LabelEntradas.setForeground(c1);
        this.LabelVariedades.setFont(subtitulo);
        this.LabelVariedades.setForeground(c1);
        this.labelContacto.setFont(subtitulo);
        this.labelContacto.setForeground(c1);;
        
        this.labelCorreo.setFont(texto);
        this.labelCorreo.setForeground(c1);
        this.labelTel.setFont(texto);
        this.labelTel.setForeground(c1);
        
        this.txtMail.setFont(texto);
        this.txtTelefono.setFont(texto);
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TituloDetalles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntradas = new javax.swing.JTable();
        txtMail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        labelCorreo = new javax.swing.JLabel();
        labelContacto = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        LabelEntradas = new javax.swing.JLabel();
        LabelVariedades = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVariedades = new javax.swing.JTable();
        panelEDITARClientes = new javax.swing.JPanel();
        botonEditarClientes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        tituloLista = new javax.swing.JLabel();
        filtroRealizados = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        panelEDITAR = new javax.swing.JPanel();
        botonEditar = new javax.swing.JLabel();
        panelAGREGAR = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JLabel();
        panelELIMINAR = new javax.swing.JPanel();
        botonELIMINAR = new javax.swing.JLabel();
        botonRecargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(165, 165, 165));

        jPanel2.setBackground(new java.awt.Color(154, 12, 26));
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 750));

        TituloDetalles.setBackground(new java.awt.Color(255, 255, 255));
        TituloDetalles.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TituloDetalles.setText("Detalles del Evento");

        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEntradas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaEntradas.setRowHeight(22);
        tablaEntradas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaEntradas);

        txtMail.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtTelefono.setPreferredSize(new java.awt.Dimension(5, 20));

        labelCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCorreo.setText("Correo Electrónico");

        labelContacto.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        labelContacto.setText("Contacto");

        labelTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTel.setText("Número Telefónico");

        LabelEntradas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LabelEntradas.setText("Entradas");

        LabelVariedades.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LabelVariedades.setText("Variedades");

        tablaVariedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVariedades.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaVariedades.setRowHeight(22);
        tablaVariedades.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaVariedades);

        panelEDITARClientes.setBackground(new java.awt.Color(48, 48, 186));

        botonEditarClientes.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        botonEditarClientes.setForeground(new java.awt.Color(255, 255, 255));
        botonEditarClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonEditarClientes.setText("Editar");
        botonEditarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
        botonEditarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEditarClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEditarClientesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEDITARClientesLayout = new javax.swing.GroupLayout(panelEDITARClientes);
        panelEDITARClientes.setLayout(panelEDITARClientesLayout);
        panelEDITARClientesLayout.setHorizontalGroup(
            panelEDITARClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonEditarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelEDITARClientesLayout.setVerticalGroup(
            panelEDITARClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEDITARClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonEditarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEntradas)
                            .addComponent(LabelVariedades)
                            .addComponent(labelContacto)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelCorreo)
                                    .addComponent(labelTel)
                                    .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(TituloDetalles)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelEDITARClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TituloDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(panelEDITARClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LabelVariedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelEntradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );

        jPanel4.setBackground(new java.awt.Color(165, 165, 165));

        GestorBD gestor = new GestorBD();
        Vector<Vector<String>> vector = gestor.dameLaTabla(0);
        Object[][] objetos = gestor.vectorObjetoConvertir(vector);
        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            objetos,
            new String [] {
                "ID","Nombre", "Adultos", "Niños", "Localidad", "Direccion", "Fecha", "Horario", "Hora","Precio","Señado", "Seña"
            }

        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }
    );
    tablaEventos.setIntercellSpacing(new java.awt.Dimension(0, 0));
    tablaEventos.setRowHeight(22);
    tablaEventos.setSelectionBackground(new java.awt.Color(48, 48, 186));
    tablaEventos.getTableHeader().setReorderingAllowed(false);
    tablaEventos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            tablaEventosMousePressed(evt);
        }
    });
    jScrollPane4.setViewportView(tablaEventos);

    jPanel6.setBackground(new java.awt.Color(165, 165, 165));

    tituloLista.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
    tituloLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    tituloLista.setText("Lista de Eventos");

    filtroRealizados.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    filtroRealizados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendientes", "Realizados", "Todos" }));
    filtroRealizados.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            filtroRealizadosMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addComponent(filtroRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(140, 140, 140)
            .addComponent(tituloLista)
            .addContainerGap(200, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tituloLista)
                .addComponent(filtroRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    jPanel7.setBackground(new java.awt.Color(165, 165, 165));

    panelEDITAR.setBackground(new java.awt.Color(48, 48, 186));

    botonEditar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
    botonEditar.setForeground(new java.awt.Color(255, 255, 255));
    botonEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    botonEditar.setText("Editar");
    botonEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            botonEditarMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            botonEditarMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            botonEditarMouseExited(evt);
        }
    });

    javax.swing.GroupLayout panelEDITARLayout = new javax.swing.GroupLayout(panelEDITAR);
    panelEDITAR.setLayout(panelEDITARLayout);
    panelEDITARLayout.setHorizontalGroup(
        panelEDITARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
    );
    panelEDITARLayout.setVerticalGroup(
        panelEDITARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    panelAGREGAR.setBackground(new java.awt.Color(48, 48, 186));
    panelAGREGAR.setAlignmentY(10.0F);

    botonAgregar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
    botonAgregar.setForeground(new java.awt.Color(255, 255, 255));
    botonAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    botonAgregar.setText("Agregar Evento");
    botonAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    botonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            botonAgregarMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            botonAgregarMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            botonAgregarMouseExited(evt);
        }
    });

    javax.swing.GroupLayout panelAGREGARLayout = new javax.swing.GroupLayout(panelAGREGAR);
    panelAGREGAR.setLayout(panelAGREGARLayout);
    panelAGREGARLayout.setHorizontalGroup(
        panelAGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
    );
    panelAGREGARLayout.setVerticalGroup(
        panelAGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(botonAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    panelELIMINAR.setBackground(new java.awt.Color(48, 48, 186));

    botonELIMINAR.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
    botonELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
    botonELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    botonELIMINAR.setText("Eliminar");
    botonELIMINAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    botonELIMINAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botonELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            botonELIMINARMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            botonELIMINARMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            botonELIMINARMouseExited(evt);
        }
    });

    javax.swing.GroupLayout panelELIMINARLayout = new javax.swing.GroupLayout(panelELIMINAR);
    panelELIMINAR.setLayout(panelELIMINARLayout);
    panelELIMINARLayout.setHorizontalGroup(
        panelELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelELIMINARLayout.createSequentialGroup()
            .addComponent(botonELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0))
    );
    panelELIMINARLayout.setVerticalGroup(
        panelELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(botonELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
            .addContainerGap(11, Short.MAX_VALUE)
            .addComponent(panelELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(92, 92, 92)
            .addComponent(panelEDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(87, 87, 87)
            .addComponent(panelAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(123, 123, 123))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(panelEDITAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelELIMINAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAGREGAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    botonRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recargar.png"))); // NOI18N
    botonRecargar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonRecargarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botonRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(jScrollPane4))
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botonRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, Short.MAX_VALUE))
            .addGap(0, 0, 0))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalizarTablaEventos(){
        tablaEventos.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 14));
        tablaEventos.getTableHeader().setOpaque(false);
        tablaEventos.getTableHeader().setBackground(Color.yellow);
        tablaEventos.getTableHeader().setForeground(new Color(20,20,20)); 
        tablaEventos.setRowHeight(30);
        tablaEventos.setFont(new Font("Roboto", Font.PLAIN,14));
        
        tablaEventos.getColumnModel().getColumn(0).setPreferredWidth(5); // id
        tablaEventos.getColumnModel().getColumn(1).setPreferredWidth(50); //nombre
        tablaEventos.getColumnModel().getColumn(2).setPreferredWidth(30); //cantAdultos
        tablaEventos.getColumnModel().getColumn(3).setPreferredWidth(20); //cantNiños
        tablaEventos.getColumnModel().getColumn(4).setPreferredWidth(50); //localidad
        tablaEventos.getColumnModel().getColumn(5).setPreferredWidth(100); //direccion
        tablaEventos.getColumnModel().getColumn(6).setPreferredWidth(40); //fecha
        tablaEventos.getColumnModel().getColumn(7).setPreferredWidth(30); //horario
        tablaEventos.getColumnModel().getColumn(8).setPreferredWidth(23); //hora
        tablaEventos.getColumnModel().getColumn(9).setPreferredWidth(18); //precio
        tablaEventos.getColumnModel().getColumn(10).setPreferredWidth(25); //señado
        tablaEventos.getColumnModel().getColumn(11).setPreferredWidth(10); //seña
    }
    
    private void personalizarTabla(JTable table){
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(Color.yellow);
        table.getTableHeader().setForeground(new Color(20,20,20)); 
        table.setRowHeight(26);
        table.setFont(new Font("Roboto",Font.PLAIN,14));
        
        table.getColumnModel().getColumn(0).setPreferredWidth(160);
        table.getColumnModel().getColumn(1).setPreferredWidth(40);
        
    }
    
    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed
    
    private void botonRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecargarActionPerformed
        recargarTabla(0);
    }//GEN-LAST:event_botonRecargarActionPerformed

    private void botonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseClicked
        
    }//GEN-LAST:event_botonEliminarMouseClicked

    private void botonELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonELIMINARMouseClicked
        int filaSeleccionada = this.tablaEventos.getSelectedRow();
        if (filaSeleccionada != -1){
            int ax = JOptionPane.showConfirmDialog(null, "¿Seguro que desea borrar este registro?");
            if(ax == JOptionPane.YES_OPTION){
                int id = Integer.valueOf((String)this.tablaEventos.getValueAt(filaSeleccionada, 0));
        
                gestor.borrarEvento(id);
                recargarTabla(0);
                JOptionPane.showMessageDialog(null, "Se ha borrado el registro");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún registro a eliminar.\nSeleccione un registro para eliminarlo.");
        }
    }//GEN-LAST:event_botonELIMINARMouseClicked

    editarEvento ee;
    private void botonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseClicked
        int filaSeleccionada = this.tablaEventos.getSelectedRow();
        if (filaSeleccionada != -1){
            int id = Integer.valueOf((String)this.tablaEventos.getValueAt(filaSeleccionada, 0));
            ee = new editarEvento(id);
            ee.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún registro a editar.\nSeleccione un registro para editarlo.");
        }
        
    }//GEN-LAST:event_botonEditarMouseClicked

    private void tablaEventosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEventosMousePressed
        int filaSeleccionada = this.tablaEventos.getSelectedRow();
        int id = Integer.valueOf((String)this.tablaEventos.getValueAt(filaSeleccionada, 0));

        Vector<Vector<String>> tabla = gestor.dameUnRegistro(id);

        //SETEAR CONTACTO
        String mail = tabla.get(0).get(0);
        this.txtMail.setText(mail);
        String tel = tabla.get(0).get(1);
        this.txtTelefono.setText(tel);

        //SETEAR VARIEDADES
        int count = 0;
        for(int i = 1 ; i < tabla.size() ; i++){
            if("variedad".equals(tabla.get(i).get(1)) || "variedadextra".equals(tabla.get(i).get(1))){
                count++;
            }
        }

        Object[][] varied = new Object[count][2];
        for(int i = 1 ; i <= count; i++){
            varied[i-1][0] = tabla.get(i).get(0);
            varied[i-1][1] = tabla.get(i).get(1);
        }

        tablaVariedades.setModel(new javax.swing.table.DefaultTableModel(
            varied,
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        //SETEAR ENTRADAS
        int count2 = 0;
        for(int i = 1 ; i < tabla.size() ; i++){
            if("entrada".equals(tabla.get(i).get(1)) || "entradaespecial".equals(tabla.get(i).get(1))){
                count2++;
            }
        }

        Object[][] entr = new Object[count2][2];
        int c = 0;
        for(int i = 1 ; i < tabla.size(); i++){
            if("entrada".equals(tabla.get(i).get(1)) || "entradaespecial".equals(tabla.get(i).get(1))){
                entr[c][0] = tabla.get(i).get(0);
                entr[c][1] = tabla.get(i).get(1);
                c++;
            }
        }

        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            entr,
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        personalizarTabla(tablaEntradas);
        personalizarTabla(tablaVariedades);
    }//GEN-LAST:event_tablaEventosMousePressed

    private void botonELIMINARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonELIMINARMouseEntered
        botonELIMINAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(100, 100, 240), new java.awt.Color(100, 120, 240), new java.awt.Color(25, 33, 136), new java.awt.Color(25, 33, 136)));
    }//GEN-LAST:event_botonELIMINARMouseEntered

    private void botonELIMINARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonELIMINARMouseExited
        botonELIMINAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    }//GEN-LAST:event_botonELIMINARMouseExited

    private void botonEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseEntered
        botonEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(100, 100, 240), new java.awt.Color(100, 120, 240), new java.awt.Color(25, 33, 136), new java.awt.Color(25, 33, 136)));
    }//GEN-LAST:event_botonEditarMouseEntered

    private void botonEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseExited
        botonEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    }//GEN-LAST:event_botonEditarMouseExited

    private void botonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseEntered
        botonAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(100, 100, 240), new java.awt.Color(100, 120, 240), new java.awt.Color(25, 33, 136), new java.awt.Color(25, 33, 136)));
    }//GEN-LAST:event_botonAgregarMouseEntered

    private void botonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseExited
        botonAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    }//GEN-LAST:event_botonAgregarMouseExited

    private void filtroRealizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtroRealizadosMouseClicked
        int seleccionado = filtroRealizados.getSelectedIndex();
        switch(seleccionado){
            case 0:
                recargarTabla(0);
                break;
            case 1:
                recargarTabla(1);
                break;
            case 2:
                recargarTabla(2);
                break;
            default:
                recargarTabla(2);
                break;
        }
    }//GEN-LAST:event_filtroRealizadosMouseClicked
    
    agregarCliente aa;
    private void botonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseClicked
        aa=new agregarCliente();
        aa.setVisible(true);
    }//GEN-LAST:event_botonAgregarMouseClicked

    editarCliente ec;
    private void botonEditarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarClientesMouseClicked
        ec=new editarCliente();
        ec.setVisible(true);
    }//GEN-LAST:event_botonEditarClientesMouseClicked

    private void botonEditarClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarClientesMouseEntered
        botonEditarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(100, 100, 240), new java.awt.Color(100, 120, 240), new java.awt.Color(25, 33, 136), new java.awt.Color(25, 33, 136)));
    }//GEN-LAST:event_botonEditarClientesMouseEntered

    private void botonEditarClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarClientesMouseExited
        botonEditarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 71, 212), new java.awt.Color(52, 65, 210), new java.awt.Color(4, 2, 136), new java.awt.Color(4, 2, 136)));
    }//GEN-LAST:event_botonEditarClientesMouseExited

    public void recargarTabla(int filtro){
        Vector<Vector<String>> vector = gestor.dameLaTabla(filtro);
        Object[][] objetos = gestor.vectorObjetoConvertir(vector);
        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            objetos,
            new String [] {
                "ID","Nombre", "Adultos", "Niños", "Localidad", "Direccion", "Fecha", "Horario", "Hora","Precio","Señado", "Seña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personalizarTablaEventos();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEntradas;
    private javax.swing.JLabel LabelVariedades;
    private javax.swing.JLabel TituloDetalles;
    private javax.swing.JLabel botonAgregar;
    private javax.swing.JLabel botonELIMINAR;
    private javax.swing.JLabel botonEditar;
    private javax.swing.JLabel botonEditarClientes;
    private javax.swing.JButton botonRecargar;
    private javax.swing.JComboBox<String> filtroRealizados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelContacto;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelTel;
    private javax.swing.JPanel panelAGREGAR;
    private javax.swing.JPanel panelEDITAR;
    private javax.swing.JPanel panelEDITARClientes;
    private javax.swing.JPanel panelELIMINAR;
    private javax.swing.JTable tablaEntradas;
    private javax.swing.JTable tablaEventos;
    private javax.swing.JTable tablaVariedades;
    private javax.swing.JLabel tituloLista;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
